#%RAML 1.0
---
title: Nevernote API - 
version: v0.1
/notebooks:
    get:
        description: Query notebooks stored in Nevernote
        queryParameters:
            query_type:
                displayName: Query Type
                type: string
                description: Query by 'notebook_id' or 'notebook_title'
                example: "notebook_id"
                required: true
            query:
                displayName: Query
                type: string or integer
                description: Query term - id or title to search for
                example: "'grocery_notebook' or '2'"
                required: true
            tag:
                displayName: Tag
                type: string
                description: Filter by a 'tag' value
                example: "funny"
                required: false
    
    post:
        description: Create or Delete notebooks
        queryParameters:
            action:
                displayName: Action
                type: string
                description: User ID for the user whom made the click.
                example: "create"
                required: true
            notebook_id:
                displayName: Notebook ID
                type: integer
                description: ID of the notebook you would like to perform operations on. Required for 'delete' action.
                example: "25"
                required: false
            title:
                displayName: Notebook Title
                type: string
                description: Title of the notebook you would like to perform operations on. Required for 'create' action.
                example: "Shopping Lists"
                required: false
    
/notes:
    get:
        description: Query notes stored in Nevernote
        queryParameters:
            query_type:
                displayName: Query Type
                type: string
                description: Query by 'note_id'
                example: "note_id"
                required: true
            query:
                displayName: Query
                type: integer
                description: Query term - what is the 'node_id' you are looking up?
                example: 43
                required: true
    
    post:
        description: Create, Delete, or Update notes
        queryParameters:
            action:
                displayName: Action
                type: string
                description: The action you would like to perform: "create", "delete", or "update"
                example: "create"
                required: true
            note_id:
                displayName: Note ID
                type: integer
                description: ID of the note you would like to perform operations on. Required for "delete" and "update" actions.
                example: 43
                required: false
            title:
                displayName: Note Title
                type: string
                description: Title of the note you are performing actions with. Required for "create" action.
                example: "Shopping List"
                required: false
            body:
                displayName: Note Body
                type: string
                description: Text body of the note you are performing actions with. Required for "create" action.
                example: "Need to buy: eggs, cheeseburgers, coffee, soup."
                required: false
            tags:
                displayName: Tags
                type: array
                items:
                    type: string
                description: List of tags (strings) to associate with the note. Required for "create" action
                example: "bdebenon"
                required: false
            notebook_id:
                displayName: Notebook ID
                type: integer
                description: Notebook ID of the note you are associating a note with. Required for "create" action.
                example: 32
                required: false
    
