#%RAML 1.0
---
title: Nevernote API - 
version: v0.1
/notebooks:
    get:
        description: Returns a list of job applications the user has already submitted.
        queryParameters:
            query_type:
                displayName: Query Type
                type: string
                description: Query by 'notebook_id' or 'notebook_title'
                example: "notebook_id"
                required: true
            query:
                displayName: Query
                type: string or integer
                description: Query term
                example: "grocery_notebook" or 2"
                required: true
            tag:
                displayName: Tag
                type: string
                description: Filter by a 'tag' value
                example: "funny"
                required: false
    
    post:
        description: Post applications to the database and queue
        queryParameters:
            user_id:
                displayName: User ID
                type: string
                description: User ID for the user whom made the click.
                example: "bdebenon"
                required: false
    
/notes:
    get:
        description: Returns a list of job applications the user has already submitted.
        queryParameters:
            user_id:
                displayName: User ID
                type: string
                description: The user ID for the accounts you are retrieving information for.
                example: "bdebenon"
                required: true
    
    post:
        description: Post applications to the database and queue
        queryParameters:
            user_id:
                displayName: User ID
                type: string
                description: User ID for the user whom made the click.
                example: "bdebenon"
                required: false
    
